### ISSUE TITLE
ERROR: name 'os' is not defined

### ISSUE THREAD

**Issue by godseye439** [vasusen-code/SaveRestrictedContentBot#1]
2022-01-26T06:00:41.368904+00:00 app[Drone.1]: [ERROR/2022-01-26 06:00:41,367] pyrogram.dispatcher: expected string or bytes-like object
2022-01-26T06:00:41.368921+00:00 app[Drone.1]: Traceback (most recent call last):
2022-01-26T06:00:41.368922+00:00 app[Drone.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-01-26T06:00:41.368922+00:00 app[Drone.1]:     await handler.callback(self.client, *args)
2022-01-26T06:00:41.368923+00:00 app[Drone.1]:   File "/app/main/plugins/main.py", line 106, in clone
2022-01-26T06:00:41.368924+00:00 app[Drone.1]:     link = get_link(event.text)
2022-01-26T06:00:41.368925+00:00 app[Drone.1]:   File "/app/main/plugins/helpers.py", line 26, in get_link
2022-01-26T06:00:41.368925+00:00 app[Drone.1]:     url = re.findall(regex,string)
2022-01-26T06:00:41.368926+00:00 app[Drone.1]:   File "/app/.heroku/python/lib/python3.9/re.py", line 241, in findall
2022-01-26T06:00:41.368926+00:00 app[Drone.1]:     return _compile(pattern, flags).findall(string)
2022-01-26T06:00:41.368927+00:00 app[Drone.1]: TypeError: expected string or bytes-like object

**Comment by godseye439** [comment]
Cloning from public channels works fine.. throws this error when trying to save from a private channel

**Comment by vasusen-code** [comment]
Fixed, try redeploying.

**Comment by godseye439** [comment]
Works! thank you
