### ISSUE TITLE
Python problem

### ISSUE THREAD

**Issue by Ali777666** [vasusen-code/SaveRestrictedContentBot#101]
Traceback (most recent call last):
  File "C:\Users\alitu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\alitu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\alitu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    import(pkg_name)
  File "C:\Users\alitu\Desktop\SaveRestrictedContentBot-master\SaveRestrictedContentBot-master\main\__init__.py", line 24, in <module>
    userbot = Client("saverestricted", session_string=SESSION, api_hash=API_HASH, api_id=API_ID)
TypeError: Client.init() got an unexpected keyword argument 'session_string'

**Comment by timgahmen** [comment]
.env File existing?
