### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dv3lood** [vasusen-code/SaveRestrictedContentBot#121]
I've deployed by docker, and had error below:

srcbot  | starting Bot ~@DroneBots
srcbot  | Traceback (most recent call last):
srcbot  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
srcbot  |     return _run_code(code, main_globals, None,
srcbot  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
srcbot  |     exec(code, run_globals)
srcbot  |   File "/app/main/__main__.py", line 16, in <module>
srcbot  |     load_plugins(plugin_name.replace(".py", ""))
srcbot  |   File "/app/main/utils.py", line 12, in load_plugins
srcbot  |     spec.loader.exec_module(load)
srcbot  |   File "<frozen importlib._bootstrap_external>", line 786, in exec_module
srcbot  |   File "<frozen importlib._bootstrap_external>", line 923, in get_code
srcbot  |   File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
srcbot  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
srcbot  |   File "main/plugins/pyroplug.py", line 209
srcbot  |     await client.copy_message(sender, chat, msg_id)
srcbot  |     ^
srcbot  | SyntaxError: invalid syntax
srcbot exited with code 1

What's going on here?

**Comment by dv3lood** [comment]
When I reset to commit b1261427a682058bac5082fab1a5508a78b1bf0f, it works. What's wrong with the newest version?

**Comment by PalashMudi** [comment]
same problem with new code.

**Comment by LDQONJ** [comment]
Add a tab indent before "await client.copy_message(sender, chat, msg_id)".
![(A4PGT$XRR`}B09I~F85$ 0](https://github.com/vasusen-code/SaveRestrictedContentBot/assets/128981031/f6e03d2d-7479-4580-bfd3-b5db9a62f18e)
