### ISSUE TITLE
hel[p

### ISSUE THREAD

**Issue by ak-47-brar** [vasusen-code/SaveRestrictedContentBot#154]
024-04-29T11:18:36.399964+00:00 app[Drone.1]: [ERROR/2024-04-29 11:18:36,398] telethon.client.updates: Unhandled exception on sett
2024-04-29T11:18:36.400021+00:00 app[Drone.1]: Traceback (most recent call last):
2024-04-29T11:18:36.400021+00:00 app[Drone.1]:   File "/app/.heroku/python/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
2024-04-29T11:18:36.400021+00:00 app[Drone.1]:     return await fut
2024-04-29T11:18:36.400022+00:00 app[Drone.1]:            ^^^^^^^^^
2024-04-29T11:18:36.400022+00:00 app[Drone.1]: asyncio.exceptions.CancelledError
2024-04-29T11:18:36.400022+00:00 app[Drone.1]: 
2024-04-29T11:18:36.400023+00:00 app[Drone.1]: The above exception was the direct cause of the following exception:
2024-04-29T11:18:36.400023+00:00 app[Drone.1]: 
2024-04-29T11:18:36.400023+00:00 app[Drone.1]: Traceback (most recent call last):
2024-04-29T11:18:36.400024+00:00 app[Drone.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
2024-04-29T11:18:36.400024+00:00 app[Drone.1]:     await callback(event)
2024-04-29T11:18:36.400025+00:00 app[Drone.1]:   File "/app/main/plugins/start.py", line 19, in sett
2024-04-29T11:18:36.400026+00:00 app[Drone.1]:     x = await conv.get_reply()
2024-04-29T11:18:36.400026+00:00 app[Drone.1]:         ^^^^^^^^^^^^^^^^^^^^^^
2024-04-29T11:18:36.400026+00:00 app[Drone.1]:   File "/app/.heroku/python/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
2024-04-29T11:18:36.400026+00:00 app[Drone.1]:     async with timeouts.timeout(timeout):
2024-04-29T11:18:36.400026+00:00 app[Drone.1]:   File "/app/.heroku/python/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
2024-04-29T11:18:36.400026+00:00 app[Drone.1]:     raise TimeoutError from exc_val
2024-04-29T11:18:36.400027+00:00 app[Drone.1]: TimeoutError

**Comment by timgahmen** [comment]
I do not know in heroku but in line 19 is a error I guess:

fast solution: delete them "set" funktion completely... never have used it till now ;-)

"fixed" start.py:

import os
from .. import bot as Drone
from telethon import events, Button
from ethon.mystarts import start_srb
    
S = '/' + 's' + 't' + 'a' + 'r' + 't'

@Drone.on(events.NewMessage(incoming=True, pattern=f"{S}"))
async def start(event):
    text = "Send me Link of any message to clone it here, For private channel message, send invite link first.\n\n**SUPPORT:** @TeamDrone"
    await start_srb(event, text)
