### ISSUE TITLE
#bug #request

### ISSUE THREAD

**Issue by Aisaeyw-hei** [vasusen-code/SaveRestrictedContentBot#66]
Sir when I use batch command it gives same files multiple times also when I updated it shows in logs
[ERROR/2022-12-30 17:48:44,284] telethon.client.updates: Unhandled exception on _batch
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
await callback(event)
File "main/plugins/batch.py", line 71, in _batch
await conv.send_message(r)
File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/conversation.py", line 88, in send_message
sent = await self._client.send_message(
File "/usr/local/lib/python3.9/site-packages/telethon/client/messages.py", line 855, in send_message
raise ValueError(
ValueError: The message cannot be empty unless a file is provided

**Comment by bolavefasfas** [comment]
Same issue

**Comment by Lr-2002** [comment]
has any one solved this problem now ?

**Comment by Aisaeyw-hei** [comment]
> has any one solved this problem now ?

Hmmm
