### ISSUE TITLE
Cannot save other pic/vid except the first one

### ISSUE THREAD

**Issue by Anthony2cc** [vasusen-code/SaveRestrictedContentBot#93]
Thx for this bot. I deployed it on render and it works fine. when i send a link that contains multiple media, the bot can only forward the first one... is there any solution?

**Comment by Anthony2cc** [comment]
May 29 11:31:22 AM  starting Bot ~@DroneBots
May 29 11:36:56 AM  [ERROR/2023-05-29 03:36:56,368] telethon.client.updates: Unhandled exception on sett
May 29 11:36:56 AM  Traceback (most recent call last):
May 29 11:36:56 AM    File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
May 29 11:36:56 AM      fut.result()
May 29 11:36:56 AM  asyncio.exceptions.CancelledError
May 29 11:36:56 AM  
May 29 11:36:56 AM  The above exception was the direct cause of the following exception:
May 29 11:36:56 AM  
May 29 11:36:56 AM  Traceback (most recent call last):
May 29 11:36:56 AM    File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
May 29 11:36:56 AM      await callback(event)
May 29 11:36:56 AM    File "main/plugins/start.py", line 19, in sett
May 29 11:36:56 AM      x = await conv.get_reply()
May 29 11:36:56 AM    File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
May 29 11:36:56 AM      raise exceptions.TimeoutError() from exc
May 29 11:36:56 AM  asyncio.exceptions.TimeoutError

**Comment by vasusen-code** [comment]
Run a batch for it, simply send the numbere of files in the album in the batch.
